### ISSUE TITLE
Check against list of known cross-browser issues

### ISSUE THREAD

**Issue by ryanbetts** [adobe/spectrum-css-grid#4]
Rachel Andrew has a comprehensive list of gridbugs. Let's make sure this implementation accounts for at least the critical ones out of the gates.
https://github.com/rachelandrew/gridbugs

Bugs that impact the concerns of this grid library and need action:
- [x] has been addressed by adding autoprefixing rules ~~Should be resolvable by just manually prefixing the few places `min-content` and `max-content` are used. Would be handled by #7 if we go that route. https://github.com/rachelandrew/gridbugs#9-min-content-and-max-content-in-track-listings~~ 

Bugs that *may* need action:
- [x] Has been fixed since ~FF 61 ~~This appears to have been fixed, but need to take a look at which versions. https://github.com/rachelandrew/gridbugs#12-space-distributed-to-empty-tracks-spanned-by-an-item-with-content~~
- [x] Ignoring for now. As per Spectrum's guidelines, the grid is not meant to be used on something as low-level as a fieldset or button ~~Only impacts fieldset and button elements. Button should definitely never be a grid container, imo. You could make a case for Fieldset in certain cases though. https://github.com/rachelandrew/gridbugs#10-some-html-elements-cant-be-grid-containers~~
